language: python
os: linux
dist: focal
python:
- 3.9
- 3.8
- 3.7
- 3.6
install:
- pip install -U tox-travis
- pip install codecov
script: tox
after_success:
- codecov
before_deploy:
- pip install -r requirements_dev.txt
- invoke dist
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: PIJ5cRV72oNmNWSMmGGW53f+MrYRLLbNKQldPlNRXihDJH8XyCiomX0R14NlHQrI8JyBZZv/VK1opyoUmW6cPJL5oyso3VXhYjuvUPjNhjgbNFv926EtJigjEIAbUZ74tJS6v+c+zIh54g28k2C2rRPXUSZl3rqC3CPU0PFZ1TmvqTweCu/Gq14ocSdEB1I5gMbA07KtSbhAS/Y4FM01vtEBht04zZupnIzLgThghuPWvAJCfIVOSlaQ8lny7ImWmUsLOdb5lG6amVZja6FITZmsXpDecc6Pk6lEyTAWs4PexbILq8UEKkLjs8GgggVEjyS4YtQlVT6n9nkihmhLDW8vjQ8jyaW+UA7JOKDubI5AuyLUrOS4yPkzAeJ8UAhH8wkfRA6WY6vhd6hxNaQIuz2J12nfpnACeBOCjwwGlwW78nB9fWZHUygfqs6Xyr40Inx0T87/UQqx+VipNuJ2wyOtjptYWUUHHRarlOHfz9scbBjbPqeX0xUH25ycVv3P4d1/lTdFRaKl2F4xwWcfkU2MR+59Uftupg2Zs/NsqL6se4uJpgNcnjVsCnTYfsceEaG+5cWnsxWZp6U6lnRkaSwc2MnoCJxPqL24Ga4LV14dNZYG7SOAvuml3d42dXPZxNSoeT7xnkaurlMLHzcJljUMjEV4cXq51Sr22XQk934=
  on:
    tags: true
    repo: engineervix/readme-coverage-badger
    python: 3.8
  skip_existing: true
  skip-cleanup: true
